### ISSUE TITLE
Doesn't seem to see or read the pgpass file. Can't log in automatically.

### ISSUE THREAD

**Issue by timuckun** [dogukancagatay/docker-pwless-pgadmin4#7]
Merhaba Dogukan.

Thanks for creating this docker container, it's frustrating that Pgadmin doesn't do it. I really appreciate the work you put into it.

When I launch the container from docker compose it is not able to log into the database I specified in the env vars. I opened up a shell in the container all the files exist, have the right permissions and contain the proper information.  Everything looks good so this is very puzzling.

I decided to copy the entrypoint and the dockerfile and did a build myself but the same result. 

The error is

```bash
devcontainer-pgadmin-1       | 2023-05-23 10:49:54,164: ERROR	pgadmin:	Could not connect to server(#1) - 'tfb-database'.
devcontainer-pgadmin-1       | Error: connection failed: fe_sendauth: no password supplied
```

Do you have any ideas as to what could be happening?

Here is the docker compose

```yaml
 pgadmin:
    image: dcagatay/pwless-pgadmin4

    # build:
    #   context: .
    #   dockerfile: Dockerfile-pgadmin4
    #   args:
    #     BASE_VERSION: 7.1
    # command: /entrypoint.sh
    depends_on:
      tfb-database:
        condition: service_started

    ports:
      - 5050:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      POSTGRES_DB: 'hello_world'
      POSTGRES_USER: 'benchmarkdbuser'
      POSTGRES_PASSWORD: 'benchmarkdbpass'
      POSTGRES_HOST: 'tfb-database'
```

Here is the generated files 

pgpass

```
tfb-database:5432:hello_world:benchmarkdbuser:benchmarkdbpass
```

servers.json
```json
{
    "Servers": {
        "1": {
            "Name": "tfb-database",
            "Group": "Servers",
            "Host": "tfb-database",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "benchmarkdbuser",
            "SSLMode": "prefer",
            "PassFile": "/var/lib/pgadmin/pgpass"
        }
    }
}
```
